use_frameworks!

target 'Flipbook_Example' do
  pod 'Flipbook', :path => '../'

  target 'Flipbook_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.1'
    pod 'Nimble', '~> 7.1.3'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
